[project]
name = "a2-mcda-5511"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "debugpy>=1.8.12",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "psutil>=7.0.0",
    "pywin32>=308",
    "pyzmq>=26.2.1",
    "seaborn>=0.13.2",
    "tornado>=6.4.2",
]
